### PR TITLE
Simplify names board_* -> * (already in the class)

### PR DESCRIPTION
**Pull request by louismartin**
I thought that the prefix board_* for attributes of the class Board and local variables could be removed for readability.
What do you think ?

### CODE REVIEW

**Comment by hassony2** [comment]
I agree with the idea.

But we will have to be careful with the potential merging conflicts with PR #9.

How do you think we should handle this ?

**Comment by hassony2** [comment]
It would probably be pretty easy to add those changes to PR #9 and merge it to master afterwards. What do you think ?

**Comment by louismartin** [comment]
Let's merge PR #9 first and handle the conflicts with this one after !

**Comment by hassony2** [comment]
Works for me !

**Review by hassony2 — APPROVED** [review]

**Comment by hassony2** [comment]
👍

**Pull request merged**
